apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sluice.fullname" . }}-worker
  labels:
    {{- include "sluice.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  serviceName: {{ include "sluice.fullname" . }}-worker-headless
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "sluice.worker-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sluice.worker-labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "sluice.worker-labels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "/entrypoint.sh"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: health
              containerPort: {{ .Values.apiPort }}
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
              readOnly: true
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.apiPort }}
            initialDelaySeconds: 2
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.apiPort }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "sluice.fullname" . }}-worker-entrypoint
            defaultMode: 0755
