// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: sluice_internal.proto

package grpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SluiceInternal_ClaimStream_FullMethodName      = "/sluice.internal.v1.SluiceInternal/ClaimStream"
	SluiceInternal_AssignmentStream_FullMethodName = "/sluice.internal.v1.SluiceInternal/AssignmentStream"
	SluiceInternal_ResultStream_FullMethodName     = "/sluice.internal.v1.SluiceInternal/ResultStream"
	SluiceInternal_AllocationPush_FullMethodName   = "/sluice.internal.v1.SluiceInternal/AllocationPush"
)

// SluiceInternalClient is the client API for SluiceInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SluiceInternalClient interface {
	// ClaimStream is the legacy rolling-upgrade path. Older workers send
	// concrete claim requests; the leader accumulates them for a configurable
	// batch window (default 5 ms), then commits one Raft log entry.
	//
	// This reduces Raft Apply calls from O(tasks) to O(batches).
	ClaimStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimRequest, ClaimBatch], error)
	// AssignmentStream is the leader-owned scheduling path. Each idle worker
	// reports one free execution slot and its preferred tenant. The leader
	// batches requests, selects distinct pending tasks, commits one ClaimBatch
	// Raft entry, and only then returns executable task payloads.
	AssignmentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignmentRequest, AssignmentBatch], error)
	// ResultStream batches task completions.  Workers stream completion
	// events to the leader, which commits them as a single Raft entry per
	// batch window.
	ResultStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResultRequest, ResultBatch], error)
	// AllocationPush replaces polling.  Nodes subscribe and the leader
	// pushes allocation plans whenever they change.
	AllocationPush(ctx context.Context, in *AllocationSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllocationPlan], error)
}

type sluiceInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewSluiceInternalClient(cc grpc.ClientConnInterface) SluiceInternalClient {
	return &sluiceInternalClient{cc}
}

func (c *sluiceInternalClient) ClaimStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClaimRequest, ClaimBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SluiceInternal_ServiceDesc.Streams[0], SluiceInternal_ClaimStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClaimRequest, ClaimBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_ClaimStreamClient = grpc.BidiStreamingClient[ClaimRequest, ClaimBatch]

func (c *sluiceInternalClient) AssignmentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssignmentRequest, AssignmentBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SluiceInternal_ServiceDesc.Streams[1], SluiceInternal_AssignmentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssignmentRequest, AssignmentBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_AssignmentStreamClient = grpc.BidiStreamingClient[AssignmentRequest, AssignmentBatch]

func (c *sluiceInternalClient) ResultStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResultRequest, ResultBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SluiceInternal_ServiceDesc.Streams[2], SluiceInternal_ResultStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResultRequest, ResultBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_ResultStreamClient = grpc.BidiStreamingClient[ResultRequest, ResultBatch]

func (c *sluiceInternalClient) AllocationPush(ctx context.Context, in *AllocationSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AllocationPlan], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SluiceInternal_ServiceDesc.Streams[3], SluiceInternal_AllocationPush_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AllocationSubscribe, AllocationPlan]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_AllocationPushClient = grpc.ServerStreamingClient[AllocationPlan]

// SluiceInternalServer is the server API for SluiceInternal service.
// All implementations must embed UnimplementedSluiceInternalServer
// for forward compatibility.
type SluiceInternalServer interface {
	// ClaimStream is the legacy rolling-upgrade path. Older workers send
	// concrete claim requests; the leader accumulates them for a configurable
	// batch window (default 5 ms), then commits one Raft log entry.
	//
	// This reduces Raft Apply calls from O(tasks) to O(batches).
	ClaimStream(grpc.BidiStreamingServer[ClaimRequest, ClaimBatch]) error
	// AssignmentStream is the leader-owned scheduling path. Each idle worker
	// reports one free execution slot and its preferred tenant. The leader
	// batches requests, selects distinct pending tasks, commits one ClaimBatch
	// Raft entry, and only then returns executable task payloads.
	AssignmentStream(grpc.BidiStreamingServer[AssignmentRequest, AssignmentBatch]) error
	// ResultStream batches task completions.  Workers stream completion
	// events to the leader, which commits them as a single Raft entry per
	// batch window.
	ResultStream(grpc.BidiStreamingServer[ResultRequest, ResultBatch]) error
	// AllocationPush replaces polling.  Nodes subscribe and the leader
	// pushes allocation plans whenever they change.
	AllocationPush(*AllocationSubscribe, grpc.ServerStreamingServer[AllocationPlan]) error
	mustEmbedUnimplementedSluiceInternalServer()
}

// UnimplementedSluiceInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSluiceInternalServer struct{}

func (UnimplementedSluiceInternalServer) ClaimStream(grpc.BidiStreamingServer[ClaimRequest, ClaimBatch]) error {
	return status.Error(codes.Unimplemented, "method ClaimStream not implemented")
}
func (UnimplementedSluiceInternalServer) AssignmentStream(grpc.BidiStreamingServer[AssignmentRequest, AssignmentBatch]) error {
	return status.Error(codes.Unimplemented, "method AssignmentStream not implemented")
}
func (UnimplementedSluiceInternalServer) ResultStream(grpc.BidiStreamingServer[ResultRequest, ResultBatch]) error {
	return status.Error(codes.Unimplemented, "method ResultStream not implemented")
}
func (UnimplementedSluiceInternalServer) AllocationPush(*AllocationSubscribe, grpc.ServerStreamingServer[AllocationPlan]) error {
	return status.Error(codes.Unimplemented, "method AllocationPush not implemented")
}
func (UnimplementedSluiceInternalServer) mustEmbedUnimplementedSluiceInternalServer() {}
func (UnimplementedSluiceInternalServer) testEmbeddedByValue()                        {}

// UnsafeSluiceInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SluiceInternalServer will
// result in compilation errors.
type UnsafeSluiceInternalServer interface {
	mustEmbedUnimplementedSluiceInternalServer()
}

func RegisterSluiceInternalServer(s grpc.ServiceRegistrar, srv SluiceInternalServer) {
	// If the following call panics, it indicates UnimplementedSluiceInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SluiceInternal_ServiceDesc, srv)
}

func _SluiceInternal_ClaimStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SluiceInternalServer).ClaimStream(&grpc.GenericServerStream[ClaimRequest, ClaimBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_ClaimStreamServer = grpc.BidiStreamingServer[ClaimRequest, ClaimBatch]

func _SluiceInternal_AssignmentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SluiceInternalServer).AssignmentStream(&grpc.GenericServerStream[AssignmentRequest, AssignmentBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_AssignmentStreamServer = grpc.BidiStreamingServer[AssignmentRequest, AssignmentBatch]

func _SluiceInternal_ResultStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SluiceInternalServer).ResultStream(&grpc.GenericServerStream[ResultRequest, ResultBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_ResultStreamServer = grpc.BidiStreamingServer[ResultRequest, ResultBatch]

func _SluiceInternal_AllocationPush_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AllocationSubscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SluiceInternalServer).AllocationPush(m, &grpc.GenericServerStream[AllocationSubscribe, AllocationPlan]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SluiceInternal_AllocationPushServer = grpc.ServerStreamingServer[AllocationPlan]

// SluiceInternal_ServiceDesc is the grpc.ServiceDesc for SluiceInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SluiceInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sluice.internal.v1.SluiceInternal",
	HandlerType: (*SluiceInternalServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClaimStream",
			Handler:       _SluiceInternal_ClaimStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AssignmentStream",
			Handler:       _SluiceInternal_AssignmentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ResultStream",
			Handler:       _SluiceInternal_ResultStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AllocationPush",
			Handler:       _SluiceInternal_AllocationPush_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sluice_internal.proto",
}
