// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sluice_internal.proto

package grpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_proto_sluice_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ClaimRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ClaimRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClaimRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ClaimBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`       // successfully claimed
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"` // already claimed by another node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimBatch) Reset() {
	*x = ClaimBatch{}
	mi := &file_proto_sluice_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimBatch) ProtoMessage() {}

func (x *ClaimBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimBatch.ProtoReflect.Descriptor instead.
func (*ClaimBatch) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimBatch) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *ClaimBatch) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "done" or "failed"
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_sluice_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ResultBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommittedIds  []string               `protobuf:"bytes,1,rep,name=committed_ids,json=committedIds,proto3" json:"committed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultBatch) Reset() {
	*x = ResultBatch{}
	mi := &file_proto_sluice_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultBatch) ProtoMessage() {}

func (x *ResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultBatch.ProtoReflect.Descriptor instead.
func (*ResultBatch) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ResultBatch) GetCommittedIds() []string {
	if x != nil {
		return x.CommittedIds
	}
	return nil
}

type AllocationSubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // which node is subscribing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationSubscribe) Reset() {
	*x = AllocationSubscribe{}
	mi := &file_proto_sluice_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationSubscribe) ProtoMessage() {}

func (x *AllocationSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationSubscribe.ProtoReflect.Descriptor instead.
func (*AllocationSubscribe) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{4}
}

func (x *AllocationSubscribe) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TenantWorkerCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Workers       int32                  `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantWorkerCount) Reset() {
	*x = TenantWorkerCount{}
	mi := &file_proto_sluice_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantWorkerCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantWorkerCount) ProtoMessage() {}

func (x *TenantWorkerCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantWorkerCount.ProtoReflect.Descriptor instead.
func (*TenantWorkerCount) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{5}
}

func (x *TenantWorkerCount) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantWorkerCount) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type AllocationPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // which node this allocation is for
	Tenants       []*TenantWorkerCount   `protobuf:"bytes,2,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationPlan) Reset() {
	*x = AllocationPlan{}
	mi := &file_proto_sluice_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationPlan) ProtoMessage() {}

func (x *AllocationPlan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sluice_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationPlan.ProtoReflect.Descriptor instead.
func (*AllocationPlan) Descriptor() ([]byte, []int) {
	return file_proto_sluice_internal_proto_rawDescGZIP(), []int{6}
}

func (x *AllocationPlan) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AllocationPlan) GetTenants() []*TenantWorkerCount {
	if x != nil {
		return x.Tenants
	}
	return nil
}

var File_proto_sluice_internal_proto protoreflect.FileDescriptor

const file_proto_sluice_internal_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/sluice_internal.proto\x12\x12sluice.internal.v1\"w\n" +
	"\fClaimRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"F\n" +
	"\n" +
	"ClaimBatch\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\"\x8b\x01\n" +
	"\rResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"2\n" +
	"\vResultBatch\x12#\n" +
	"\rcommitted_ids\x18\x01 \x03(\tR\fcommittedIds\".\n" +
	"\x13AllocationSubscribe\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"J\n" +
	"\x11TenantWorkerCount\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\x05R\aworkers\"j\n" +
	"\x0eAllocationPlan\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12?\n" +
	"\atenants\x18\x02 \x03(\v2%.sluice.internal.v1.TenantWorkerCountR\atenants2\x9e\x02\n" +
	"\x0eSluiceInternal\x12S\n" +
	"\vClaimStream\x12 .sluice.internal.v1.ClaimRequest\x1a\x1e.sluice.internal.v1.ClaimBatch(\x010\x01\x12V\n" +
	"\fResultStream\x12!.sluice.internal.v1.ResultRequest\x1a\x1f.sluice.internal.v1.ResultBatch(\x010\x01\x12_\n" +
	"\x0eAllocationPush\x12'.sluice.internal.v1.AllocationSubscribe\x1a\".sluice.internal.v1.AllocationPlan0\x01B-Z+github.com/day253/sluice/pkg/grpc/v1;grpcv1b\x06proto3"

var (
	file_proto_sluice_internal_proto_rawDescOnce sync.Once
	file_proto_sluice_internal_proto_rawDescData []byte
)

func file_proto_sluice_internal_proto_rawDescGZIP() []byte {
	file_proto_sluice_internal_proto_rawDescOnce.Do(func() {
		file_proto_sluice_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sluice_internal_proto_rawDesc), len(file_proto_sluice_internal_proto_rawDesc)))
	})
	return file_proto_sluice_internal_proto_rawDescData
}

var file_proto_sluice_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_sluice_internal_proto_goTypes = []any{
	(*ClaimRequest)(nil),        // 0: sluice.internal.v1.ClaimRequest
	(*ClaimBatch)(nil),          // 1: sluice.internal.v1.ClaimBatch
	(*ResultRequest)(nil),       // 2: sluice.internal.v1.ResultRequest
	(*ResultBatch)(nil),         // 3: sluice.internal.v1.ResultBatch
	(*AllocationSubscribe)(nil), // 4: sluice.internal.v1.AllocationSubscribe
	(*TenantWorkerCount)(nil),   // 5: sluice.internal.v1.TenantWorkerCount
	(*AllocationPlan)(nil),      // 6: sluice.internal.v1.AllocationPlan
}
var file_proto_sluice_internal_proto_depIdxs = []int32{
	5, // 0: sluice.internal.v1.AllocationPlan.tenants:type_name -> sluice.internal.v1.TenantWorkerCount
	0, // 1: sluice.internal.v1.SluiceInternal.ClaimStream:input_type -> sluice.internal.v1.ClaimRequest
	2, // 2: sluice.internal.v1.SluiceInternal.ResultStream:input_type -> sluice.internal.v1.ResultRequest
	4, // 3: sluice.internal.v1.SluiceInternal.AllocationPush:input_type -> sluice.internal.v1.AllocationSubscribe
	1, // 4: sluice.internal.v1.SluiceInternal.ClaimStream:output_type -> sluice.internal.v1.ClaimBatch
	3, // 5: sluice.internal.v1.SluiceInternal.ResultStream:output_type -> sluice.internal.v1.ResultBatch
	6, // 6: sluice.internal.v1.SluiceInternal.AllocationPush:output_type -> sluice.internal.v1.AllocationPlan
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_sluice_internal_proto_init() }
func file_proto_sluice_internal_proto_init() {
	if File_proto_sluice_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sluice_internal_proto_rawDesc), len(file_proto_sluice_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sluice_internal_proto_goTypes,
		DependencyIndexes: file_proto_sluice_internal_proto_depIdxs,
		MessageInfos:      file_proto_sluice_internal_proto_msgTypes,
	}.Build()
	File_proto_sluice_internal_proto = out.File
	file_proto_sluice_internal_proto_goTypes = nil
	file_proto_sluice_internal_proto_depIdxs = nil
}
