// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/sluice.proto

package grpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sluice_Submit_FullMethodName        = "/sluice.v1.Sluice/Submit"
	Sluice_GetTask_FullMethodName       = "/sluice.v1.Sluice/GetTask"
	Sluice_WaitTask_FullMethodName      = "/sluice.v1.Sluice/WaitTask"
	Sluice_UpsertTenant_FullMethodName  = "/sluice.v1.Sluice/UpsertTenant"
	Sluice_DeleteTenant_FullMethodName  = "/sluice.v1.Sluice/DeleteTenant"
	Sluice_ListTenants_FullMethodName   = "/sluice.v1.Sluice/ListTenants"
	Sluice_ClusterStatus_FullMethodName = "/sluice.v1.Sluice/ClusterStatus"
	Sluice_Health_FullMethodName        = "/sluice.v1.Sluice/Health"
	Sluice_SubmitBatch_FullMethodName   = "/sluice.v1.Sluice/SubmitBatch"
)

// SluiceClient is the client API for Sluice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SluiceClient interface {
	// Submit a task and receive its result via server-side streaming.
	// The server streams status updates (pending → inflight → done/failed)
	// then closes the stream on completion.
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubmitEvent], error)
	// Get the current status of a task.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskStatus, error)
	// Wait for a task to complete (long-polling equivalent).
	// Returns immediately if already done; blocks with periodic updates otherwise.
	WaitTask(ctx context.Context, in *WaitTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubmitEvent], error)
	// Admin: upsert a tenant configuration.
	UpsertTenant(ctx context.Context, in *UpsertTenantRequest, opts ...grpc.CallOption) (*UpsertTenantResponse, error)
	// Admin: delete a tenant.
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	// Admin: list all tenants.
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// Admin: list cluster nodes and allocations.
	ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Bidirectional streaming for high-throughput task submission.
	// Clients stream tasks in; server streams results back as they complete.
	SubmitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitRequest, SubmitEvent], error)
}

type sluiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSluiceClient(cc grpc.ClientConnInterface) SluiceClient {
	return &sluiceClient{cc}
}

func (c *sluiceClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubmitEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sluice_ServiceDesc.Streams[0], Sluice_Submit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubmitRequest, SubmitEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_SubmitClient = grpc.ServerStreamingClient[SubmitEvent]

func (c *sluiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, Sluice_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) WaitTask(ctx context.Context, in *WaitTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubmitEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sluice_ServiceDesc.Streams[1], Sluice_WaitTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaitTaskRequest, SubmitEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_WaitTaskClient = grpc.ServerStreamingClient[SubmitEvent]

func (c *sluiceClient) UpsertTenant(ctx context.Context, in *UpsertTenantRequest, opts ...grpc.CallOption) (*UpsertTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTenantResponse)
	err := c.cc.Invoke(ctx, Sluice_UpsertTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, Sluice_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, Sluice_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, Sluice_ClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Sluice_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sluiceClient) SubmitBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubmitRequest, SubmitEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sluice_ServiceDesc.Streams[2], Sluice_SubmitBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubmitRequest, SubmitEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_SubmitBatchClient = grpc.BidiStreamingClient[SubmitRequest, SubmitEvent]

// SluiceServer is the server API for Sluice service.
// All implementations must embed UnimplementedSluiceServer
// for forward compatibility.
type SluiceServer interface {
	// Submit a task and receive its result via server-side streaming.
	// The server streams status updates (pending → inflight → done/failed)
	// then closes the stream on completion.
	Submit(*SubmitRequest, grpc.ServerStreamingServer[SubmitEvent]) error
	// Get the current status of a task.
	GetTask(context.Context, *GetTaskRequest) (*TaskStatus, error)
	// Wait for a task to complete (long-polling equivalent).
	// Returns immediately if already done; blocks with periodic updates otherwise.
	WaitTask(*WaitTaskRequest, grpc.ServerStreamingServer[SubmitEvent]) error
	// Admin: upsert a tenant configuration.
	UpsertTenant(context.Context, *UpsertTenantRequest) (*UpsertTenantResponse, error)
	// Admin: delete a tenant.
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	// Admin: list all tenants.
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// Admin: list cluster nodes and allocations.
	ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Bidirectional streaming for high-throughput task submission.
	// Clients stream tasks in; server streams results back as they complete.
	SubmitBatch(grpc.BidiStreamingServer[SubmitRequest, SubmitEvent]) error
	mustEmbedUnimplementedSluiceServer()
}

// UnimplementedSluiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSluiceServer struct{}

func (UnimplementedSluiceServer) Submit(*SubmitRequest, grpc.ServerStreamingServer[SubmitEvent]) error {
	return status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedSluiceServer) GetTask(context.Context, *GetTaskRequest) (*TaskStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedSluiceServer) WaitTask(*WaitTaskRequest, grpc.ServerStreamingServer[SubmitEvent]) error {
	return status.Error(codes.Unimplemented, "method WaitTask not implemented")
}
func (UnimplementedSluiceServer) UpsertTenant(context.Context, *UpsertTenantRequest) (*UpsertTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTenant not implemented")
}
func (UnimplementedSluiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedSluiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedSluiceServer) ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClusterStatus not implemented")
}
func (UnimplementedSluiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSluiceServer) SubmitBatch(grpc.BidiStreamingServer[SubmitRequest, SubmitEvent]) error {
	return status.Error(codes.Unimplemented, "method SubmitBatch not implemented")
}
func (UnimplementedSluiceServer) mustEmbedUnimplementedSluiceServer() {}
func (UnimplementedSluiceServer) testEmbeddedByValue()                {}

// UnsafeSluiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SluiceServer will
// result in compilation errors.
type UnsafeSluiceServer interface {
	mustEmbedUnimplementedSluiceServer()
}

func RegisterSluiceServer(s grpc.ServiceRegistrar, srv SluiceServer) {
	// If the following call panics, it indicates UnimplementedSluiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sluice_ServiceDesc, srv)
}

func _Sluice_Submit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubmitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SluiceServer).Submit(m, &grpc.GenericServerStream[SubmitRequest, SubmitEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_SubmitServer = grpc.ServerStreamingServer[SubmitEvent]

func _Sluice_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_WaitTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WaitTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SluiceServer).WaitTask(m, &grpc.GenericServerStream[WaitTaskRequest, SubmitEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_WaitTaskServer = grpc.ServerStreamingServer[SubmitEvent]

func _Sluice_UpsertTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).UpsertTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_UpsertTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).UpsertTenant(ctx, req.(*UpsertTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_ClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).ClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_ClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).ClusterStatus(ctx, req.(*ClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SluiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sluice_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SluiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sluice_SubmitBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SluiceServer).SubmitBatch(&grpc.GenericServerStream[SubmitRequest, SubmitEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sluice_SubmitBatchServer = grpc.BidiStreamingServer[SubmitRequest, SubmitEvent]

// Sluice_ServiceDesc is the grpc.ServiceDesc for Sluice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sluice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sluice.v1.Sluice",
	HandlerType: (*SluiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _Sluice_GetTask_Handler,
		},
		{
			MethodName: "UpsertTenant",
			Handler:    _Sluice_UpsertTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _Sluice_DeleteTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _Sluice_ListTenants_Handler,
		},
		{
			MethodName: "ClusterStatus",
			Handler:    _Sluice_ClusterStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Sluice_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Submit",
			Handler:       _Sluice_Submit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WaitTask",
			Handler:       _Sluice_WaitTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubmitBatch",
			Handler:       _Sluice_SubmitBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sluice.proto",
}
