// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sluice.proto

package grpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_sluice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // always "pending" on submit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_sluice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubmitBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*SubmitRequest       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatchRequest) Reset() {
	*x = SubmitBatchRequest{}
	mi := &file_sluice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchRequest) ProtoMessage() {}

func (x *SubmitBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitBatchRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitBatchRequest) GetTasks() []*SubmitRequest {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type SubmitBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*SubmitResponse      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitBatchResponse) Reset() {
	*x = SubmitBatchResponse{}
	mi := &file_sluice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitBatchResponse) ProtoMessage() {}

func (x *SubmitBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitBatchResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitBatchResponse) GetTasks() []*SubmitResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_sluice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "inflight", "done", "failed"
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_sluice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TaskStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskStatus) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WaitTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = default (30s)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WaitTaskRequest) Reset() {
	*x = WaitTaskRequest{}
	mi := &file_sluice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitTaskRequest) ProtoMessage() {}

func (x *WaitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitTaskRequest.ProtoReflect.Descriptor instead.
func (*WaitTaskRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{6}
}

func (x *WaitTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WaitTaskRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type UpsertTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxWorkers    int32                  `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantRequest) Reset() {
	*x = UpsertTenantRequest{}
	mi := &file_sluice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantRequest) ProtoMessage() {}

func (x *UpsertTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantRequest.ProtoReflect.Descriptor instead.
func (*UpsertTenantRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{7}
}

func (x *UpsertTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpsertTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertTenantRequest) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

type UpsertTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTenantResponse) Reset() {
	*x = UpsertTenantResponse{}
	mi := &file_sluice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTenantResponse) ProtoMessage() {}

func (x *UpsertTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTenantResponse.ProtoReflect.Descriptor instead.
func (*UpsertTenantResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{8}
}

func (x *UpsertTenantResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_sluice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_sluice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTenantResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_sluice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{11}
}

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxWorkers    int32                  `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	Inflight      int32                  `protobuf:"varint,4,opt,name=inflight,proto3" json:"inflight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_sluice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{12}
}

func (x *TenantInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantInfo) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

func (x *TenantInfo) GetInflight() int32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_sluice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{13}
}

func (x *ListTenantsResponse) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusRequest) Reset() {
	*x = ClusterStatusRequest{}
	mi := &file_sluice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusRequest) ProtoMessage() {}

func (x *ClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*ClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{14}
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RaftAddress   string                 `protobuf:"bytes,3,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalWorkers  int32                  `protobuf:"varint,5,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_sluice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{15}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInfo) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

type TenantAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Workers       int32                  `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantAllocation) Reset() {
	*x = TenantAllocation{}
	mi := &file_sluice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAllocation) ProtoMessage() {}

func (x *TenantAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantAllocation.ProtoReflect.Descriptor instead.
func (*TenantAllocation) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{16}
}

func (x *TenantAllocation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantAllocation) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type NodeAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tenants       []*TenantAllocation    `protobuf:"bytes,2,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAllocation) Reset() {
	*x = NodeAllocation{}
	mi := &file_sluice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAllocation) ProtoMessage() {}

func (x *NodeAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAllocation.ProtoReflect.Descriptor instead.
func (*NodeAllocation) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{17}
}

func (x *NodeAllocation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeAllocation) GetTenants() []*TenantAllocation {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ClusterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Allocations   []*NodeAllocation      `protobuf:"bytes,2,rep,name=allocations,proto3" json:"allocations,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,3,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatusResponse) Reset() {
	*x = ClusterStatusResponse{}
	mi := &file_sluice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatusResponse) ProtoMessage() {}

func (x *ClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*ClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{18}
}

func (x *ClusterStatusResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ClusterStatusResponse) GetAllocations() []*NodeAllocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *ClusterStatusResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sluice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Leader        string                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sluice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sluice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sluice_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

var File_sluice_proto protoreflect.FileDescriptor

const file_sluice_proto_rawDesc = "" +
	"\n" +
	"\fsluice.proto\x12\tsluice.v1\"o\n" +
	"\rSubmitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"^\n" +
	"\x0eSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"D\n" +
	"\x12SubmitBatchRequest\x12.\n" +
	"\x05tasks\x18\x01 \x03(\v2\x18.sluice.v1.SubmitRequestR\x05tasks\"F\n" +
	"\x13SubmitBatchResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.sluice.v1.SubmitResponseR\x05tasks\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x88\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"S\n" +
	"\x0fWaitTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"g\n" +
	"\x13UpsertTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\x05R\n" +
	"maxWorkers\"&\n" +
	"\x14UpsertTenantResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"2\n" +
	"\x13DeleteTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"&\n" +
	"\x14DeleteTenantResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x14\n" +
	"\x12ListTenantsRequest\"z\n" +
	"\n" +
	"TenantInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\x05R\n" +
	"maxWorkers\x12\x1a\n" +
	"\binflight\x18\x04 \x01(\x05R\binflight\"F\n" +
	"\x13ListTenantsResponse\x12/\n" +
	"\atenants\x18\x01 \x03(\v2\x15.sluice.v1.TenantInfoR\atenants\"\x16\n" +
	"\x14ClusterStatusRequest\"\x9d\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fraft_address\x18\x03 \x01(\tR\vraftAddress\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rtotal_workers\x18\x05 \x01(\x05R\ftotalWorkers\"I\n" +
	"\x10TenantAllocation\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\x05R\aworkers\"`\n" +
	"\x0eNodeAllocation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\atenants\x18\x02 \x03(\v2\x1b.sluice.v1.TenantAllocationR\atenants\"\xa6\x01\n" +
	"\x15ClusterStatusResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.sluice.v1.NodeInfoR\x05nodes\x12;\n" +
	"\vallocations\x18\x02 \x03(\v2\x19.sluice.v1.NodeAllocationR\vallocations\x12%\n" +
	"\x0eleader_address\x18\x03 \x01(\tR\rleaderAddress\"\x0f\n" +
	"\rHealthRequest\"Y\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader2\x94\x05\n" +
	"\x06Sluice\x12=\n" +
	"\x06Submit\x12\x18.sluice.v1.SubmitRequest\x1a\x19.sluice.v1.SubmitResponse\x12L\n" +
	"\vSubmitBatch\x12\x1d.sluice.v1.SubmitBatchRequest\x1a\x1e.sluice.v1.SubmitBatchResponse\x12;\n" +
	"\aGetTask\x12\x19.sluice.v1.GetTaskRequest\x1a\x15.sluice.v1.TaskStatus\x12=\n" +
	"\bWaitTask\x12\x1a.sluice.v1.WaitTaskRequest\x1a\x15.sluice.v1.TaskStatus\x12O\n" +
	"\fUpsertTenant\x12\x1e.sluice.v1.UpsertTenantRequest\x1a\x1f.sluice.v1.UpsertTenantResponse\x12O\n" +
	"\fDeleteTenant\x12\x1e.sluice.v1.DeleteTenantRequest\x1a\x1f.sluice.v1.DeleteTenantResponse\x12L\n" +
	"\vListTenants\x12\x1d.sluice.v1.ListTenantsRequest\x1a\x1e.sluice.v1.ListTenantsResponse\x12R\n" +
	"\rClusterStatus\x12\x1f.sluice.v1.ClusterStatusRequest\x1a .sluice.v1.ClusterStatusResponse\x12=\n" +
	"\x06Health\x12\x18.sluice.v1.HealthRequest\x1a\x19.sluice.v1.HealthResponseB-Z+github.com/day253/sluice/pkg/grpc/v1;grpcv1b\x06proto3"

var (
	file_sluice_proto_rawDescOnce sync.Once
	file_sluice_proto_rawDescData []byte
)

func file_sluice_proto_rawDescGZIP() []byte {
	file_sluice_proto_rawDescOnce.Do(func() {
		file_sluice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sluice_proto_rawDesc), len(file_sluice_proto_rawDesc)))
	})
	return file_sluice_proto_rawDescData
}

var file_sluice_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sluice_proto_goTypes = []any{
	(*SubmitRequest)(nil),         // 0: sluice.v1.SubmitRequest
	(*SubmitResponse)(nil),        // 1: sluice.v1.SubmitResponse
	(*SubmitBatchRequest)(nil),    // 2: sluice.v1.SubmitBatchRequest
	(*SubmitBatchResponse)(nil),   // 3: sluice.v1.SubmitBatchResponse
	(*GetTaskRequest)(nil),        // 4: sluice.v1.GetTaskRequest
	(*TaskStatus)(nil),            // 5: sluice.v1.TaskStatus
	(*WaitTaskRequest)(nil),       // 6: sluice.v1.WaitTaskRequest
	(*UpsertTenantRequest)(nil),   // 7: sluice.v1.UpsertTenantRequest
	(*UpsertTenantResponse)(nil),  // 8: sluice.v1.UpsertTenantResponse
	(*DeleteTenantRequest)(nil),   // 9: sluice.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),  // 10: sluice.v1.DeleteTenantResponse
	(*ListTenantsRequest)(nil),    // 11: sluice.v1.ListTenantsRequest
	(*TenantInfo)(nil),            // 12: sluice.v1.TenantInfo
	(*ListTenantsResponse)(nil),   // 13: sluice.v1.ListTenantsResponse
	(*ClusterStatusRequest)(nil),  // 14: sluice.v1.ClusterStatusRequest
	(*NodeInfo)(nil),              // 15: sluice.v1.NodeInfo
	(*TenantAllocation)(nil),      // 16: sluice.v1.TenantAllocation
	(*NodeAllocation)(nil),        // 17: sluice.v1.NodeAllocation
	(*ClusterStatusResponse)(nil), // 18: sluice.v1.ClusterStatusResponse
	(*HealthRequest)(nil),         // 19: sluice.v1.HealthRequest
	(*HealthResponse)(nil),        // 20: sluice.v1.HealthResponse
}
var file_sluice_proto_depIdxs = []int32{
	0,  // 0: sluice.v1.SubmitBatchRequest.tasks:type_name -> sluice.v1.SubmitRequest
	1,  // 1: sluice.v1.SubmitBatchResponse.tasks:type_name -> sluice.v1.SubmitResponse
	12, // 2: sluice.v1.ListTenantsResponse.tenants:type_name -> sluice.v1.TenantInfo
	16, // 3: sluice.v1.NodeAllocation.tenants:type_name -> sluice.v1.TenantAllocation
	15, // 4: sluice.v1.ClusterStatusResponse.nodes:type_name -> sluice.v1.NodeInfo
	17, // 5: sluice.v1.ClusterStatusResponse.allocations:type_name -> sluice.v1.NodeAllocation
	0,  // 6: sluice.v1.Sluice.Submit:input_type -> sluice.v1.SubmitRequest
	2,  // 7: sluice.v1.Sluice.SubmitBatch:input_type -> sluice.v1.SubmitBatchRequest
	4,  // 8: sluice.v1.Sluice.GetTask:input_type -> sluice.v1.GetTaskRequest
	6,  // 9: sluice.v1.Sluice.WaitTask:input_type -> sluice.v1.WaitTaskRequest
	7,  // 10: sluice.v1.Sluice.UpsertTenant:input_type -> sluice.v1.UpsertTenantRequest
	9,  // 11: sluice.v1.Sluice.DeleteTenant:input_type -> sluice.v1.DeleteTenantRequest
	11, // 12: sluice.v1.Sluice.ListTenants:input_type -> sluice.v1.ListTenantsRequest
	14, // 13: sluice.v1.Sluice.ClusterStatus:input_type -> sluice.v1.ClusterStatusRequest
	19, // 14: sluice.v1.Sluice.Health:input_type -> sluice.v1.HealthRequest
	1,  // 15: sluice.v1.Sluice.Submit:output_type -> sluice.v1.SubmitResponse
	3,  // 16: sluice.v1.Sluice.SubmitBatch:output_type -> sluice.v1.SubmitBatchResponse
	5,  // 17: sluice.v1.Sluice.GetTask:output_type -> sluice.v1.TaskStatus
	5,  // 18: sluice.v1.Sluice.WaitTask:output_type -> sluice.v1.TaskStatus
	8,  // 19: sluice.v1.Sluice.UpsertTenant:output_type -> sluice.v1.UpsertTenantResponse
	10, // 20: sluice.v1.Sluice.DeleteTenant:output_type -> sluice.v1.DeleteTenantResponse
	13, // 21: sluice.v1.Sluice.ListTenants:output_type -> sluice.v1.ListTenantsResponse
	18, // 22: sluice.v1.Sluice.ClusterStatus:output_type -> sluice.v1.ClusterStatusResponse
	20, // 23: sluice.v1.Sluice.Health:output_type -> sluice.v1.HealthResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sluice_proto_init() }
func file_sluice_proto_init() {
	if File_sluice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sluice_proto_rawDesc), len(file_sluice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sluice_proto_goTypes,
		DependencyIndexes: file_sluice_proto_depIdxs,
		MessageInfos:      file_sluice_proto_msgTypes,
	}.Build()
	File_sluice_proto = out.File
	file_sluice_proto_goTypes = nil
	file_sluice_proto_depIdxs = nil
}
